services:
  web:
    image: youcefmei/crudpersonweb:latest
    ports:
      - "9001:9001"
    environment:
        - API_URL=http://api:9000
    depends_on:
      - db
      - api
    healthcheck:
      test: curl --fail http://api:9000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  db:
    image: mysql:9.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springboot
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/springboot}
    depends_on:
      - db
    image: youcefmei/crudpersonapi:latest
